ITEMS_PER_PAGE = 12
SKILL_AUTOCOMPLETE_LIMIT = 8

SKILL_NAME_MAX_LENGTH = 80
PROJECT_NAME_MAX_LENGTH = 140
STATUS_MAX_LENGTH = 20

USER_NAME_MAX_LENGTH = 80
USER_SURNAME_MAX_LENGTH = 80
PHONE_MAX_LENGTH = 30
